# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P9_JXoquGfHJHcIbvSSm-ZNkJntPyDQI
"""

print("Hello World")

a=5
b=2
("Hello World")

a=7.5
b=7.5
c=4
h=b**2-0.5*c**2
S=0.5*h*c
print(S)

a=2
b=6
c=9
x=(a**2+b**2-c**3)/2
print(x)

a=5
b=input()
print(a*b)

a = float(input("Введите первое число: "))
b = float(input("Введите второе число: "))
x = float(0)
y = float(0)
x = a + b
y = x * x
print(y)

a = 15
b = 10
c = float(input())
x = a + b
y = x/c
print(y)

a = float(input("Введите первое число: "))
b = float(input("Введите второе число: "))
x = a**2+2*a*b+b**2
print(x)

a=float(input("Введите первое число: "))
b=float(input("Введите второе число: "))
c=float(input("Введите третье число: "))
h=b**2-0.5*c**2
S=0.5*h*c
P=a+b+c
print(S)
print(P)

a=float(input("Введите первое число: "))
b=float(input("Введите второе число: "))
x = ((a**3 + 14)/5)*b
print(x)

a=float(input("Введите первое число: "))
n=float(input("Введите второе число: "))
x = a**2/n
print(x)

from traitlets.utils.importstring import import_item
from re import I
c=float(input("Введите первое число: "))
i=c
x = c//i
print(x)
a = x*x
b = c%i
print(a)
print(b)

a = float(input())
x = a/60/60/24
print(" days " + str(x))
b = a/60/60
print(b)
c = a/60
print(c)

n = 9
x = n+n*n+n*n*n
print(x)